FROM openshift/origin-release:golang-1.10
COPY . /go/src/github.com/kubernetes-csi/external-provisioner/
RUN cd /go/src/github.com/kubernetes-csi/external-provisioner/ && \
    go build ./cmd/csi-provisioner

FROM centos:7

COPY --from=0 /go/src/github.com/kubernetes-csi/external-provisioner/csi-provisioner /usr/bin/

RUN useradd csi-provisioner
USER csi-provisioner

CMD ["/usr/bin/csi-provisioner"]
