FROM registry.svc.ci.openshift.org/ocp/builder:golang-1.10 AS builder
WORKDIR /go/src/github.com/kubernetes-csi/external-provisioner
COPY . .
RUN go build ./cmd/csi-provisioner

FROM registry.svc.ci.openshift.org/ocp/4.0:base
COPY --from=builder /go/src/github.com/kubernetes-csi/external-provisioner/csi-provisioner /usr/bin/
RUN useradd csi-provisioner
USER csi-provisioner
ENTRYPOINT ["/usr/bin/csi-provisioner"]
